"""
Azure AI Search service for hierarchical ETL schema indexing.

Creates an index that mirrors the JSON structure defined in
`project_plan/etl_schema.json` and uploads ETL documents generated by
the pipeline's JSON writer.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

from azure.core.credentials import AzureKeyCredential
from azure.search.documents import SearchClient
from azure.search.documents.indexes import SearchIndexClient
from azure.search.documents.indexes.models import (
    AzureOpenAIVectorizer,
    AzureOpenAIVectorizerParameters,
    HnswAlgorithmConfiguration,
    HnswParameters,
    SearchField,
    SearchFieldDataType,
    SearchIndex,
    VectorSearch,
    VectorSearchProfile,
)

from src.config import AzureOpenAIConfig, AzureSearchConfig
from src.etl.models.etl_models import ETLDocument

logger = logging.getLogger(__name__)


class ETLSearchService:
    """
    Service for Azure AI Search operations using ETL hierarchical schema.

    Provides index creation and upload methods for `ETLDocument` and JSON files
    that conform to the schema in `project_plan/etl_schema.json`.
    """

    def __init__(self, search_config: AzureSearchConfig, openai_config: AzureOpenAIConfig):
        self.search_config = search_config
        self.openai_config = openai_config

        credential = AzureKeyCredential(search_config.key)

        # Choose ETL index name if provided; fallback to default index
        self.index_name = getattr(search_config, "etl_index_name", None) or search_config.index_name

        self.index_client = SearchIndexClient(endpoint=search_config.endpoint, credential=credential)
        self.search_client = SearchClient(
            endpoint=search_config.endpoint, index_name=self.index_name, credential=credential
        )

        logger.info(f"Initialized ETLSearchService: {search_config.endpoint}/{self.index_name}")

    def create_index(self, recreate: bool = False) -> bool:
        """
        Create Azure AI Search index aligned to hierarchical ETL schema.

        Returns True if index created or already exists.
        """
        try:
            existing = [idx.name for idx in self.index_client.list_indexes()]
            if self.index_name in existing:
                if recreate:
                    logger.warning(f"Deleting existing ETL index: {self.index_name}")
                    self.index_client.delete_index(self.index_name)
                else:
                    logger.info(f"ETL index already exists: {self.index_name}")
                    return True

            embedding_dims = self.openai_config.embedding_dimensions or 1536

            # Helper: vector field
            def vec_field(name: str) -> SearchField:
                return SearchField(
                    name=name,
                    type=SearchFieldDataType.Collection(SearchFieldDataType.Single),
                    searchable=True,
                    vector_search_dimensions=embedding_dims,
                    vector_search_profile_name="etlHnswProfile",
                )

            # Define hierarchical fields
            fields: list[SearchField] = [
                SearchField(name="doc_id", type=SearchFieldDataType.String, key=True, filterable=True),
                SearchField(name="filename", type=SearchFieldDataType.String, searchable=True, filterable=True),

                # file_metadata (complex)
                SearchField(
                    name="file_metadata",
                    type=SearchFieldDataType.Complex,
                    fields=[
                        SearchField(name="file_name", type=SearchFieldDataType.String, searchable=True),
                        SearchField(name="file_path", type=SearchFieldDataType.String, retrievable=True),
                        SearchField(name="file_size_bytes", type=SearchFieldDataType.Int64, filterable=True),
                        SearchField(name="file_type", type=SearchFieldDataType.String, filterable=True),
                        SearchField(name="library_name", type=SearchFieldDataType.String, searchable=True, filterable=True),
                        SearchField(name="category_name", type=SearchFieldDataType.String, searchable=True, filterable=True),
                        SearchField(name="title_name", type=SearchFieldDataType.String, searchable=True),
                        SearchField(name="file_url", type=SearchFieldDataType.String, retrievable=True),
                        SearchField(name="branch_name", type=SearchFieldDataType.String, filterable=True),
                        SearchField(name="document_language", type=SearchFieldDataType.String, filterable=True),
                        SearchField(name="last_updated", type=SearchFieldDataType.DateTimeOffset, filterable=True),
                        SearchField(name="page_count", type=SearchFieldDataType.Int32, filterable=True),
                        SearchField(name="extracted_at", type=SearchFieldDataType.DateTimeOffset, filterable=True),
                        SearchField(name="processing_version", type=SearchFieldDataType.String, filterable=True),
                    ],
                ),

                # file_summary (complex with vector)
                SearchField(
                    name="file_summary",
                    type=SearchFieldDataType.Complex,
                    fields=[
                        SearchField(name="file_function_summary", type=SearchFieldDataType.String, searchable=True),
                        vec_field("file_summary_vector"),
                    ],
                ),

                # keyword_extraction (complex)
                SearchField(
                    name="keyword_extraction",
                    type=SearchFieldDataType.Complex,
                    fields=[
                        SearchField(name="entities", type=SearchFieldDataType.Collection(SearchFieldDataType.String), searchable=True),
                        SearchField(name="product_names", type=SearchFieldDataType.Collection(SearchFieldDataType.String), searchable=True),
                        SearchField(name="topics", type=SearchFieldDataType.Collection(SearchFieldDataType.String), searchable=True),
                        SearchField(name="file_type", type=SearchFieldDataType.String, filterable=True),
                        SearchField(name="key_phrases", type=SearchFieldDataType.Collection(SearchFieldDataType.String), searchable=True),
                    ],
                ),

                # pages (collection of complex)
                SearchField(
                    name="pages",
                    type=SearchFieldDataType.Collection(SearchFieldDataType.Complex),
                    fields=[
                        SearchField(name="page_number", type=SearchFieldDataType.Int32, filterable=True),
                        SearchField(
                            name="page_summary",
                            type=SearchFieldDataType.Complex,
                            fields=[
                                SearchField(name="page_function_summary", type=SearchFieldDataType.String, searchable=True),
                                vec_field("page_summary_vector"),
                            ],
                        ),
                        SearchField(
                            name="page_metadata",
                            type=SearchFieldDataType.Complex,
                            fields=[
                                SearchField(name="page_width", type=SearchFieldDataType.Double),
                                SearchField(name="page_height", type=SearchFieldDataType.Double),
                                SearchField(name="page_orientation", type=SearchFieldDataType.String, filterable=True),
                                SearchField(name="has_images", type=SearchFieldDataType.Boolean, filterable=True),
                                SearchField(name="has_tables", type=SearchFieldDataType.Boolean, filterable=True),
                                SearchField(name="image_count", type=SearchFieldDataType.Int32, filterable=True),
                                SearchField(name="table_count", type=SearchFieldDataType.Int32, filterable=True),
                            ],
                        ),
                        SearchField(
                            name="chunks",
                            type=SearchFieldDataType.Collection(SearchFieldDataType.Complex),
                            fields=[
                                SearchField(name="chunk_id", type=SearchFieldDataType.String, filterable=True),
                                SearchField(name="chunk_text", type=SearchFieldDataType.String, searchable=True),
                                SearchField(name="chunk_position", type=SearchFieldDataType.Int32, filterable=True),
                                SearchField(name="chunk_type", type=SearchFieldDataType.String, filterable=True),
                                SearchField(name="chunk_semantic_density", type=SearchFieldDataType.Double, filterable=True),
                                SearchField(
                                    name="chunk_metadata",
                                    type=SearchFieldDataType.Complex,
                                    fields=[
                                        SearchField(name="char_count", type=SearchFieldDataType.Int32),
                                        SearchField(name="word_count", type=SearchFieldDataType.Int32),
                                        SearchField(name="sentence_count", type=SearchFieldDataType.Int32),
                                        SearchField(
                                            name="bbox",
                                            type=SearchFieldDataType.Complex,
                                            fields=[
                                                SearchField(name="x", type=SearchFieldDataType.Double),
                                                SearchField(name="y", type=SearchFieldDataType.Double),
                                                SearchField(name="width", type=SearchFieldDataType.Double),
                                                SearchField(name="height", type=SearchFieldDataType.Double),
                                            ],
                                        ),
                                    ],
                                ),
                                vec_field("content_chunk_vector"),
                            ],
                        ),
                    ],
                ),

                # synthetic_qa_pairs (collection of complex)
                SearchField(
                    name="synthetic_qa_pairs",
                    type=SearchFieldDataType.Collection(SearchFieldDataType.Complex),
                    fields=[
                        SearchField(name="question", type=SearchFieldDataType.String, searchable=True),
                        SearchField(name="answer", type=SearchFieldDataType.String, searchable=True),
                        SearchField(name="qa_doc_id", type=SearchFieldDataType.String, filterable=True),
                        SearchField(name="qa_page_number", type=SearchFieldDataType.Int32, filterable=True),
                        SearchField(name="qa_chunk_ids", type=SearchFieldDataType.Collection(SearchFieldDataType.String)),
                        SearchField(name="qa_confidence", type=SearchFieldDataType.Double, filterable=True),
                    ],
                ),

                # tables (collection of complex)
                SearchField(
                    name="tables",
                    type=SearchFieldDataType.Collection(SearchFieldDataType.Complex),
                    fields=[
                        SearchField(name="table_id", type=SearchFieldDataType.String, filterable=True),
                        SearchField(name="page_number", type=SearchFieldDataType.Int32, filterable=True),
                        SearchField(name="table_position", type=SearchFieldDataType.Int32, filterable=True),
                        SearchField(name="table_html", type=SearchFieldDataType.String, retrievable=True),
                        SearchField(name="table_markdown", type=SearchFieldDataType.String, searchable=True),
                        SearchField(name="table_csv", type=SearchFieldDataType.String, retrievable=True),
                        SearchField(name="table_caption", type=SearchFieldDataType.String, searchable=True),
                        SearchField(name="table_summary", type=SearchFieldDataType.String, searchable=True),
                        SearchField(name="column_headers", type=SearchFieldDataType.Collection(SearchFieldDataType.String), searchable=True),
                        SearchField(name="row_count", type=SearchFieldDataType.Int32, filterable=True),
                        SearchField(name="column_count", type=SearchFieldDataType.Int32, filterable=True),
                        SearchField(
                            name="bbox",
                            type=SearchFieldDataType.Complex,
                            fields=[
                                SearchField(name="x", type=SearchFieldDataType.Double),
                                SearchField(name="y", type=SearchFieldDataType.Double),
                                SearchField(name="width", type=SearchFieldDataType.Double),
                                SearchField(name="height", type=SearchFieldDataType.Double),
                            ],
                        ),
                    ],
                ),

                # images (collection of complex)
                SearchField(
                    name="images",
                    type=SearchFieldDataType.Collection(SearchFieldDataType.Complex),
                    fields=[
                        SearchField(name="image_id", type=SearchFieldDataType.String, filterable=True),
                        SearchField(name="page_number", type=SearchFieldDataType.Int32, filterable=True),
                        SearchField(name="image_position", type=SearchFieldDataType.Int32, filterable=True),
                        SearchField(name="image_url", type=SearchFieldDataType.String, retrievable=True),
                        SearchField(name="image_caption", type=SearchFieldDataType.String, searchable=True),
                        SearchField(name="image_description", type=SearchFieldDataType.String, searchable=True),
                        SearchField(name="image_type", type=SearchFieldDataType.String, filterable=True),
                        SearchField(name="width", type=SearchFieldDataType.Int32),
                        SearchField(name="height", type=SearchFieldDataType.Int32),
                        SearchField(
                            name="bbox",
                            type=SearchFieldDataType.Complex,
                            fields=[
                                SearchField(name="x", type=SearchFieldDataType.Double),
                                SearchField(name="y", type=SearchFieldDataType.Double),
                                SearchField(name="width", type=SearchFieldDataType.Double),
                                SearchField(name="height", type=SearchFieldDataType.Double),
                            ],
                        ),
                    ],
                ),

                # processing_metadata (complex)
                SearchField(
                    name="processing_metadata",
                    type=SearchFieldDataType.Complex,
                    fields=[
                        SearchField(name="ocr_applied", type=SearchFieldDataType.Boolean, filterable=True),
                        SearchField(name="ocr_confidence", type=SearchFieldDataType.Double, filterable=True),
                        SearchField(name="total_chunks", type=SearchFieldDataType.Int32, filterable=True),
                        SearchField(name="total_tables", type=SearchFieldDataType.Int32, filterable=True),
                        SearchField(name="total_images", type=SearchFieldDataType.Int32, filterable=True),
                        SearchField(name="processing_time_seconds", type=SearchFieldDataType.Double, filterable=True),
                        SearchField(
                            name="errors",
                            type=SearchFieldDataType.Collection(SearchFieldDataType.Complex),
                            fields=[
                                SearchField(name="message", type=SearchFieldDataType.String, searchable=True),
                                SearchField(name="stage", type=SearchFieldDataType.String, filterable=True),
                                SearchField(name="details", type=SearchFieldDataType.String, retrievable=True),
                            ],
                        ),
                        SearchField(name="warnings", type=SearchFieldDataType.Collection(SearchFieldDataType.String), searchable=True),
                    ],
                ),
            ]

            # Configure vector search
            vector_search = VectorSearch(
                algorithms=[
                    HnswAlgorithmConfiguration(
                        name="etlHnsw",
                        parameters=HnswParameters(metric="cosine", m=4, ef_construction=400, ef_search=500),
                    )
                ],
                profiles=[
                    VectorSearchProfile(
                        name="etlHnswProfile", algorithm_configuration_name="etlHnsw", vectorizer_name="etlOpenAI"
                    )
                ],
                vectorizers=[
                    AzureOpenAIVectorizer(
                        vectorizer_name="etlOpenAI",
                        parameters=AzureOpenAIVectorizerParameters(
                            resource_url=self.openai_config.endpoint,
                            deployment_name=self.openai_config.deployment_name,
                            api_key=self.openai_config.key,
                        ),
                    )
                ],
            )

            index = SearchIndex(name=self.index_name, fields=fields, vector_search=vector_search)
            self.index_client.create_index(index)
            logger.info(f"Created ETL index: {self.index_name}")
            return True
        except Exception as e:
            logger.error(f"Failed to create ETL index: {str(e)}")
            return False

    def upload_etl_document(self, etl_doc: ETLDocument) -> bool:
        """Upload a single ETLDocument to the ETL index."""
        try:
            payload = etl_doc.model_dump()  # dict aligned to schema
            result = self.search_client.upload_documents(documents=[payload])
            if result[0].succeeded:
                logger.debug(f"Uploaded ETL doc: {etl_doc.doc_id}")
                return True
            logger.error(f"Failed to upload ETL doc {etl_doc.doc_id}: {result[0].error_message}")
            return False
        except Exception as e:
            logger.error(f"Exception uploading ETL doc {etl_doc.doc_id}: {str(e)}")
            return False

    def upload_etl_json(self, json_path: Path) -> bool:
        """Upload an ETL JSON file to the ETL index."""
        try:
            data = json_path.read_text(encoding="utf-8")
            # Avoid importing json at module top to keep lightweight
            import json as _json

            payload = _json.loads(data)
            result = self.search_client.upload_documents(documents=[payload])
            if result[0].succeeded:
                logger.debug(f"Uploaded ETL JSON: {json_path}")
                return True
            logger.error(f"Failed to upload ETL JSON {json_path}: {result[0].error_message}")
            return False
        except Exception as e:
            logger.error(f"Exception uploading ETL JSON {json_path}: {str(e)}")
            return False

    def index_exists(self) -> bool:
        try:
            existing = [idx.name for idx in self.index_client.list_indexes()]
            return self.index_name in existing
        except Exception:
            return False

    def get_document_count(self) -> int:
        try:
            return self.search_client.get_document_count()
        except Exception:
            return 0

    def close(self):
        logger.info("ETLSearchService close: no-op")


# Example usage
if __name__ == "__main__":
    import sys
    from src.config import get_config

    logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s")
    try:
        config = get_config()
        service = ETLSearchService(config.azure_search, config.azure_openai)
        print(f"ETL Index: {service.index_name}")
        if service.index_exists():
            print("✅ ETL index exists")
            print(f"📊 Document count: {service.get_document_count()}")
        else:
            print("❌ ETL index does not exist. Creating...")
            ok = service.create_index()
            print("✅ Created" if ok else "❌ Failed to create")
        service.close()
    except Exception as e:
        print(f"Error: {str(e)}", file=sys.stderr)
        import traceback
        traceback.print_exc()
        sys.exit(1)

